# App version: 2026.09.23.15-WEB
[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/inventory"
  to = "/.netlify/functions/inventory"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/customer"
  to = "/.netlify/functions/customer"
  status = 200
